### ISSUE TITLE
Dynamic Line#449

### ISSUE THREAD

**Issue by MayaGans** [software-tools-in-javascript/js4ds#101]
https://github.com/software-tools-in-javascript/js4ds/blob/8cf9d11c92d5967543420d979c963d1460a57f26/dynamic.tex#L449

Where do I go to see this?

**Comment by gvwilson** [comment]
When you run parcel, you should get a `dist` folder in your project. (`dist` is listed in `.gitignore` so that this folder's contents won't wind up in version control.)
