### ISSUE TITLE
/_en/Pages Lines 138-143

### ISSUE THREAD

**Issue by MayaGans** [software-tools-in-javascript/js4ds#17]
```js
const counter = () => {
  const paragraphs = document.querySelectorAll('p')
  return paragraphs.length
}
const fill = document.getElementById('fill')
fill.innerHTML = `number of paragraphs: ${counter()}`
```
This did **not** result in seeing `number of paragraphs: 2` on the page! Currently, the HTML includes `<div class="fill"></div>`. If I change it to `<div id="fill"></div>` then the code does run as desired. I tried looking for the function getElementByClassName but it did not work either. Why have we specified the class as fill rather than the id here?

**Comment by gvwilson** [comment]
This was a mistake on my part - I've updated source files, and both `src/pages/count-paragraphs.html` and `src/pages/show-paragraphs.html` now work properly for me. Should be fixed in #85.
