### ISSUE TITLE
/_en/pages.md Line 243-248

### ISSUE THREAD

**Issue by MayaGans** [software-tools-in-javascript/js4ds#25]
I tried substituting this chunk in place of the console.log() line

```js
  const container = document.getElementById('fill')
  const headings = Array.from(document.querySelectorAll('h2'))
  const items = headings
        .map((h) => `<li><a href="#${h.id}">${h.innerHTML}</a></li>`)
        .join('')
  container.innerHTML = '<ul>' + items + '</ul>'
```

Again I got the error 
```
Uncaught TypeError: Cannot set property 'innerHTML' of null
```

**Comment by gvwilson** [comment]
I'm struggling to locate this in the LaTeX source (where line numbers are different from the old Markdown line numbers).   If this is the first example in the section "Creating a Table of Contents", then the source file is `src/pages/create-toc.html`, which works fine when I open it - can you please check and confirm?

**Comment by gvwilson** [comment]
See also #17 and #85.

**Comment by MayaGans** [comment]
Addressed and fixed elsewhere
