### ISSUE TITLE
/_en/promises.md Line 394-401

### ISSUE THREAD

**Issue by MayaGans** [software-tools-in-javascript/js4ds#4]
Running:

```js
const fs = require('fs-extra')

let total_size = 0
const files = ['jane-eyre.txt', 'moby-dick.txt',
               'life-of-frederick-douglass.txt']
Promise.all(files.map(f => fs.stat(f))).
  then(stats => stats.reduce((total, s) => {return total + s.size}, 0)).
  then(console.log)
```

Resulted in the following error **(not `2594901`)**
```
DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is this error also because I don't have these text files in some directory? It seems like I need some additional directions in order to be able to run this code and the following chunks pertaining to these txt files.

**Comment by tobyhodges** [comment]
The `DeprecationWarning` is a good thing but didn't exist when this section was originally written. It means that we need to have a `.catch()` to handle exceptions for all our Promises. It should be easy enough to add these throughout the chapter/book but we should add an explanation somewhere that catching is a requirement now.

You'll find the books (Moby Dick etc) as text files squirreled away in `src/promises/`.

**Comment by MayaGans** [comment]
See issue #102
