### ISSUE TITLE
Include solutions to exercises?

### ISSUE THREAD

**Issue by tobyhodges** [software-tools-in-javascript/js4ds#83]
Is it time for us to start adding solutions to exercises, where appropriate? This seems only fair.

**Comment by gvwilson** [comment]
Should they be added to the book, or only available on the website?

**Comment by tobyhodges** [comment]
I think online-only is the best setup: my guess is that most people will want to compare their code to the solutions, which is considerably easier to do on a computer. I don't think it would add enough value to be worth the extra pages in the dead tree version. Just a note such as below should suffice:

> Solutions to exercises can be found with the online version of this book: https://js4ds.org/#s:solutions

I think solutions would only be necessary for exercises that require the reader to actually write some code.

**Comment by unode** [comment]
As a reader, I found the lack of closure for some exercises a frustrating.
Not having the solution or answer doesn't allow confirming if my thought process or answer is correct or "the right way".

Particularly relevant in cases where the exercise asks the reader to reason over what might be wrong and the causes for it. For example, even now I'm not sure if the answer to [What's going on?](https://js4ds.org/#s:promises-exercises) is the missing `;` or if there's something else to learn there.

**Comment by unode** [comment]
That said, it did force me to spend time on them so I won't forget the answers as easily if I just glanced over the displayed solution.

**Comment by asbates** [comment]
I could help with providing solutions if that is something you all want.

**Comment by GabrieleLabanca** [comment]
I don't have a definite opinion, but back in university my professor said that having solutions drives laziness: the temptation of not trying our best is just very strong if we have a shortcut. For me, it works: without solutions I am forced to understand if I have understood, and get acquainted with looking up in documentation. Moreover, it is a feedback for authors: if something is missing or is not perfectly clear, someone will throw an issue (again, it is the case for me).

**Comment by ethanone1** [comment]
A lack of solutions only drives laziness for the undisciplined. Further, there is a natural consequence for such laziness that will quickly correct it.

Including solutions, however, has great benefits to those disciplined enough to do the work. 1) it verifies that they have grasped the concepts, 2) that their problem solving skills are good, and if their problem solving skills are limited, it opens their minds to alternative approaches (i.e. could I have solved it _better_?) and 3) if they just can't solve it, they can learn from the solution.

To the last point, its rather elitist to withhold the solution. Its as if to say, "if you can't figure it out, you don't deserve the answer."

JavaScript has many intricacies not found in other languages and many ways to solve problems. Even if you come from another language, do not underestimate the power of learning from others' code.

**Comment by gvwilson** [comment]
I don't consider myself elitist, and I think the nature of this material shows that I'm unlikely to underestimate the power of learning from other's code. Once revisions are wrapped up, I will be happy to start accepting contributed solutions from readers.

**Comment by stevejryan** [comment]
For what it's worth I just found this thread because I'm working through js4ds (which is wonderful, thank you so much!) and I *also* can't figure out how you would use a reduce() function in the solution to that exercise. Doesn't mean anyone needs to do anything about it, but I feel better knowing others are also confused 😛
