### ISSUE TITLE
Need greek LGR encoding to build PDF

### ISSUE THREAD

**Issue by chendaniely** [software-tools-in-javascript/js4ds#93]
I have a full `texlive` installation on my Arch linux machine, and I still needed to install `texlive-langgreek` (on a mac it would be `greek-fontenc`, debian it would be `texlive-lang-greek` [1])
to get `make pdf` to build.

Here is the error I was getting when I was trying to build the PDF

```
Since I do not know what the LGR encoding meansI can't typeset Greek.
I stop here, while you get a suitable lgrenc.def file.
```

[1]: https://tex.stackexchange.com/questions/229143/after-installing-textgreek-lgrenc-def-still-not-available

**Comment by gvwilson** [comment]
I'm using pdfTeX 3.14159265-2.6-1.40.20 (TeX Live 2019) on a Mac, and am unable to reproduce - I don't believe there are any Greek characters in our text at this point.
